// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD5jaFXFW4AY6GjF0lVcUfqTr24LH5SGBk',
    appId: '1:488096899292:web:70b4295a0c57ea94e0d419',
    messagingSenderId: '488096899292',
    projectId: 'iot-compost-project',
    authDomain: 'iot-compost-project.firebaseapp.com',
    storageBucket: 'iot-compost-project.firebasestorage.app',
    measurementId: 'G-G3VDKGJEB9',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBlIgoc53qtBaOHFjZQcctW7sxoqrRtdL0',
    appId: '1:488096899292:android:026db191c1b214f2e0d419',
    messagingSenderId: '488096899292',
    projectId: 'iot-compost-project',
    storageBucket: 'iot-compost-project.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC_0_ZuIuVwGEHalfTYfxLTC2KRJ4EZ3M8',
    appId: '1:488096899292:ios:349f0704edf820a0e0d419',
    messagingSenderId: '488096899292',
    projectId: 'iot-compost-project',
    storageBucket: 'iot-compost-project.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC_0_ZuIuVwGEHalfTYfxLTC2KRJ4EZ3M8',
    appId: '1:488096899292:ios:349f0704edf820a0e0d419',
    messagingSenderId: '488096899292',
    projectId: 'iot-compost-project',
    storageBucket: 'iot-compost-project.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD5jaFXFW4AY6GjF0lVcUfqTr24LH5SGBk',
    appId: '1:488096899292:web:5e6cebba9e3bcf17e0d419',
    messagingSenderId: '488096899292',
    projectId: 'iot-compost-project',
    authDomain: 'iot-compost-project.firebaseapp.com',
    storageBucket: 'iot-compost-project.firebasestorage.app',
    measurementId: 'G-X8W8XQZX9H',
  );

}